In [1]:
import pandas as pd

In [2]:
code_sheet = pd.read_csv("Resources/all-geocodes-v2020.csv")

In [3]:
code_sheet.head()

,Summary Level,State Code (FIPS),County Code (FIPS),County Subdivision Code (FIPS),Place Code (FIPS),Consolidtated City Code (FIPS),Area Name (including legal/statistical area description)
0,10,0,0,0,0,0,United States
1,40,1,0,0,0,0,Alabama
2,50,1,1,0,0,0,Autauga County
3,50,1,3,0,0,0,Baldwin County
4,50,1,5,0,0,0,Barbour County

In [4]:
code_sheet.dtypes

Summary Level                                                int64
State Code (FIPS)                                            int64
County Code (FIPS)                                           int64
County Subdivision Code (FIPS)                               int64
Place Code (FIPS)                                            int64
Consolidtated City Code (FIPS)                               int64
Area Name (including legal/statistical area description)    object
dtype: object

In [5]:
code_sheet['Place Code (FIPS)'].unique()

array([    0,   124,   460, ..., 84925, 85015, 86665], dtype=int64)

In [6]:
code_sheet.head()

,Summary Level,State Code (FIPS),County Code (FIPS),County Subdivision Code (FIPS),Place Code (FIPS),Consolidtated City Code (FIPS),Area Name (including legal/statistical area description)
0,10,0,0,0,0,0,United States
1,40,1,0,0,0,0,Alabama
2,50,1,1,0,0,0,Autauga County
3,50,1,3,0,0,0,Baldwin County
4,50,1,5,0,0,0,Barbour County

In [8]:
code_states = code_sheet[code_sheet['Summary Level'] == 40]
code_states.head()

,Summary Level,State Code (FIPS),County Code (FIPS),County Subdivision Code (FIPS),Place Code (FIPS),Consolidtated City Code (FIPS),Area Name (including legal/statistical area description)
1,40,1,0,0,0,0,Alabama
531,40,2,0,0,0,0,Alaska
711,40,4,0,0,0,0,Arizona
818,40,5,0,0,0,0,Arkansas
1395,40,6,0,0,0,0,California

In [9]:
code_states.tail()

,Summary Level,State Code (FIPS),County Code (FIPS),County Subdivision Code (FIPS),Place Code (FIPS),Consolidtated City Code (FIPS),Area Name (including legal/statistical area description)
40441,40,53,0,0,0,0,Washington
40762,40,54,0,0,0,0,West Virginia
41050,40,55,0,0,0,0,Wisconsin
43636,40,56,0,0,0,0,Wyoming
43759,40,72,0,0,0,0,Puerto Rico

In [10]:
crime_data = pd.read_csv("Resources/nanda_crime_county_2002-2014_01P.csv")

In [11]:
crime_data.head()

,STCOFIPS,FIPS_ST,FIPS_CTY,YEAR,STUDYNO,EDITION,PART,IDNO,CPOPARST,CPOPCRIM,...,VIOL,PROPERTY,MURDER,RAPE,ROBBERY,AGASSLT,BURGLRY,LARCENY,MVTHEFT,ARSON
0,1001,1,1,2002,ICPSR Study No,"1st ed, August 2004",Crimes-County,1,44959,24424,...,NaN,NaN,0,18,35,48,172,1023,48,13
1,1001,1,1,2003,4360,"1st ed, August 2004",Crimes-County,1,46808,45749,...,NaN,NaN,3,29,34,95,326,1235,107,3
2,1001,1,1,2004,4466,"1st ed, August 2004",Crimes-County,1,47929,45898,...,NaN,NaN,0,11,38,103,358,1162,86,3
3,1001,1,1,2005,4717,"1st ed, August 2004",Crimes-County,1,48917,47669,...,NaN,NaN,0,15,28,67,356,1149,112,1
4,1001,1,1,2006,23780,"1st ed, August 2004",Crimes-County,1,50316,49052,...,NaN,NaN,1,16,49,85,343,1226,94,3

In [12]:
crime_data.columns

Index(['STCOFIPS', 'FIPS_ST', 'FIPS_CTY', 'YEAR', 'STUDYNO', 'EDITION', 'PART',
       'IDNO', 'CPOPARST', 'CPOPCRIM', 'AG_ARRST', 'AG_OFF', 'COVIND', 'INDEX',
       'MODINDX', 'VIOL', 'PROPERTY', 'MURDER', 'RAPE', 'ROBBERY', 'AGASSLT',
       'BURGLRY', 'LARCENY', 'MVTHEFT', 'ARSON'],
      dtype='object')

In [13]:
crime_data_renamed = crime_data.rename(columns={'FIPS_ST': 'State Code (FIPS)',
                                                'FIPS_CTY': 'County Code (FIPS)',
                                                'YEAR': 'year',
                                                'MURDER': 'murder',
                                                'RAPE': 'rape',
                                                'ROBBERY': 'robbery',
                                                'AGASSLT': 'aggravated_assaults',
                                                'BURGLRY': 'burglary',
                                                'LARCENY': 'larceny',
                                                'MVTHEFT': 'auto_theft',
                                                'ARSON': 'arson'})

In [14]:
crime_data_small = crime_data_renamed.drop(columns=['STCOFIPS', 'STUDYNO', 'EDITION', 'PART', 'IDNO', 'CPOPARST',
                                            'CPOPCRIM', 'AG_ARRST', 'AG_OFF', 'COVIND', 'INDEX', 'MODINDX',
                                            'VIOL', 'PROPERTY'])

In [15]:
crime_data_small.head()

,State Code (FIPS),County Code (FIPS),year,murder,rape,robbery,aggravated_assaults,burglary,larceny,auto_theft,arson
0,1,1,2002,0,18,35,48,172,1023,48,13
1,1,1,2003,3,29,34,95,326,1235,107,3
2,1,1,2004,0,11,38,103,358,1162,86,3
3,1,1,2005,0,15,28,67,356,1149,112,1
4,1,1,2006,1,16,49,85,343,1226,94,3

In [16]:
state_merge = pd.merge(code_states, crime_data_small, on = 'State Code (FIPS)', how = 'inner')
state_merge.head()

,Summary Level,State Code (FIPS),County Code (FIPS)_x,County Subdivision Code (FIPS),Place Code (FIPS),Consolidtated City Code (FIPS),Area Name (including legal/statistical area description),County Code (FIPS)_y,year,murder,rape,robbery,aggravated_assaults,burglary,larceny,auto_theft,arson
0,40,1,0,0,0,0,Alabama,1,2002,0,18,35,48,172,1023,48,13
1,40,1,0,0,0,0,Alabama,1,2003,3,29,34,95,326,1235,107,3
2,40,1,0,0,0,0,Alabama,1,2004,0,11,38,103,358,1162,86,3
3,40,1,0,0,0,0,Alabama,1,2005,0,15,28,67,356,1149,112,1
4,40,1,0,0,0,0,Alabama,1,2006,1,16,49,85,343,1226,94,3

In [19]:
state_merge.to_csv('Resources/merge_state.csv')

In [17]:
state_merge.shape

(41118, 17)

In [18]:
state_merge.dropna()

,Summary Level,State Code (FIPS),County Code (FIPS)_x,County Subdivision Code (FIPS),Place Code (FIPS),Consolidtated City Code (FIPS),Area Name (including legal/statistical area description),County Code (FIPS)_y,year,murder,rape,robbery,aggravated_assaults,burglary,larceny,auto_theft,arson
0,40,1,0,0,0,0,Alabama,1,2002,0,18,35,48,172,1023,48,13
1,40,1,0,0,0,0,Alabama,1,2003,3,29,34,95,326,1235,107,3
2,40,1,0,0,0,0,Alabama,1,2004,0,11,38,103,358,1162,86,3
3,40,1,0,0,0,0,Alabama,1,2005,0,15,28,67,356,1149,112,1
4,40,1,0,0,0,0,Alabama,1,2006,1,16,49,85,343,1226,94,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41113,40,56,0,0,0,0,Wyoming,777,2010,0,1,1,49,11,61,35,2
41114,40,56,0,0,0,0,Wyoming,777,2011,3,6,1,72,14,35,21,3
41115,40,56,0,0,0,0,Wyoming,777,2012,0,3,0,37,13,45,21,8
41116,40,56,0,0,0,0,Wyoming,777,2013,1,5,0,37,11,42,24,9
41117,40,56,0,0,0,0,Wyoming,777,2014,3,5,0,66,14,89,25,1

In [21]:
state_merge = state_merge.rename(columns = {'County Code (FIPS)_y': 'County Code (FIPS)'})
state_merge.head()

,Summary Level,State Code (FIPS),County Code (FIPS)_x,County Subdivision Code (FIPS),Place Code (FIPS),Consolidtated City Code (FIPS),Area Name (including legal/statistical area description),County Code (FIPS),year,murder,rape,robbery,aggravated_assaults,burglary,larceny,auto_theft,arson
0,40,1,0,0,0,0,Alabama,1,2002,0,18,35,48,172,1023,48,13
1,40,1,0,0,0,0,Alabama,1,2003,3,29,34,95,326,1235,107,3
2,40,1,0,0,0,0,Alabama,1,2004,0,11,38,103,358,1162,86,3
3,40,1,0,0,0,0,Alabama,1,2005,0,15,28,67,356,1149,112,1
4,40,1,0,0,0,0,Alabama,1,2006,1,16,49,85,343,1226,94,3

In [27]:
state_county_merge = pd.merge(code_sheet, state_merge, on = 'County Code (FIPS)', how = 'inner')
state_county_merge.head()

,Summary Level_x,State Code (FIPS)_x,County Code (FIPS),County Subdivision Code (FIPS)_x,Place Code (FIPS)_x,Consolidtated City Code (FIPS)_x,Area Name (including legal/statistical area description)_x,Summary Level_y,State Code (FIPS)_y,County Code (FIPS)_x,...,Area Name (including legal/statistical area description)_y,year,murder,rape,robbery,aggravated_assaults,burglary,larceny,auto_theft,arson
0,50,1,1,0,0,0,Autauga County,40,1,0,...,Alabama,2002,0,18,35,48,172,1023,48,13
1,50,1,1,0,0,0,Autauga County,40,1,0,...,Alabama,2003,3,29,34,95,326,1235,107,3
2,50,1,1,0,0,0,Autauga County,40,1,0,...,Alabama,2004,0,11,38,103,358,1162,86,3
3,50,1,1,0,0,0,Autauga County,40,1,0,...,Alabama,2005,0,15,28,67,356,1149,112,1
4,50,1,1,0,0,0,Autauga County,40,1,0,...,Alabama,2006,1,16,49,85,343,1226,94,3

In [29]:
state_county_merge.tail()

,Summary Level_x,State Code (FIPS)_x,County Code (FIPS),County Subdivision Code (FIPS)_x,Place Code (FIPS)_x,Consolidtated City Code (FIPS)_x,Area Name (including legal/statistical area description)_x,Summary Level_y,State Code (FIPS)_y,County Code (FIPS)_x,...,Area Name (including legal/statistical area description)_y,year,murder,rape,robbery,aggravated_assaults,burglary,larceny,auto_theft,arson
10506283,61,55,78,50975,0,0,Menominee town,40,55,0,...,Wisconsin,2010,0,0,0,3,24,28,7,1
10506284,61,55,78,50975,0,0,Menominee town,40,55,0,...,Wisconsin,2011,0,0,0,1,21,19,1,0
10506285,61,55,78,50975,0,0,Menominee town,40,55,0,...,Wisconsin,2012,0,0,0,2,31,25,3,0
10506286,61,55,78,50975,0,0,Menominee town,40,55,0,...,Wisconsin,2013,0,1,0,4,16,15,2,0
10506287,61,55,78,50975,0,0,Menominee town,40,55,0,...,Wisconsin,2014,0,0,0,0,12,21,0,0

In [32]:
state_county_merge.dropna()

,Summary Level_x,State Code (FIPS)_x,County Code (FIPS),County Subdivision Code (FIPS)_x,Place Code (FIPS)_x,Consolidtated City Code (FIPS)_x,Area Name (including legal/statistical area description)_x,Summary Level_y,State Code (FIPS)_y,County Code (FIPS)_x,...,Area Name (including legal/statistical area description)_y,year,murder,rape,robbery,aggravated_assaults,burglary,larceny,auto_theft,arson
0,50,1,1,0,0,0,Autauga County,40,1,0,...,Alabama,2002,0,18,35,48,172,1023,48,13
1,50,1,1,0,0,0,Autauga County,40,1,0,...,Alabama,2003,3,29,34,95,326,1235,107,3
2,50,1,1,0,0,0,Autauga County,40,1,0,...,Alabama,2004,0,11,38,103,358,1162,86,3
3,50,1,1,0,0,0,Autauga County,40,1,0,...,Alabama,2005,0,15,28,67,356,1149,112,1
4,50,1,1,0,0,0,Autauga County,40,1,0,...,Alabama,2006,1,16,49,85,343,1226,94,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10506283,61,55,78,50975,0,0,Menominee town,40,55,0,...,Wisconsin,2010,0,0,0,3,24,28,7,1
10506284,61,55,78,50975,0,0,Menominee town,40,55,0,...,Wisconsin,2011,0,0,0,1,21,19,1,0
10506285,61,55,78,50975,0,0,Menominee town,40,55,0,...,Wisconsin,2012,0,0,0,2,31,25,3,0
10506286,61,55,78,50975,0,0,Menominee town,40,55,0,...,Wisconsin,2013,0,1,0,4,16,15,2,0
10506287,61,55,78,50975,0,0,Menominee town,40,55,0,...,Wisconsin,2014,0,0,0,0,12,21,0,0

In [34]:
crime_df_final = state_county_merge.rename(columns = {'Area Name (including legal/statistical area description)_x': 'County',
                                                     'Area Name (including legal/statistical area description)_y': 'State'})

In [41]:
only_county = crime_df_final[crime_df_final['Summary Level_x'] != 61]
only_county.shape

(1244984, 23)

In [40]:
only_county = only_county[only_county['Summary Level_x'] != 162]
only_county.shape

(10506288, 23)

In [42]:
only_county = only_county[only_county['Summary Level_x'] != 170]
only_county.shape

(1244984, 23)

In [44]:
only_county.tail()

,Summary Level_x,State Code (FIPS)_x,County Code (FIPS),County Subdivision Code (FIPS)_x,Place Code (FIPS)_x,Consolidtated City Code (FIPS)_x,County,Summary Level_y,State Code (FIPS)_y,County Code (FIPS)_x,...,State,year,murder,rape,robbery,aggravated_assaults,burglary,larceny,auto_theft,arson
10506270,50,55,78,0,0,0,Menominee County,40,55,0,...,Wisconsin,2010,0,0,0,3,24,28,7,1
10506271,50,55,78,0,0,0,Menominee County,40,55,0,...,Wisconsin,2011,0,0,0,1,21,19,1,0
10506272,50,55,78,0,0,0,Menominee County,40,55,0,...,Wisconsin,2012,0,0,0,2,31,25,3,0
10506273,50,55,78,0,0,0,Menominee County,40,55,0,...,Wisconsin,2013,0,1,0,4,16,15,2,0
10506274,50,55,78,0,0,0,Menominee County,40,55,0,...,Wisconsin,2014,0,0,0,0,12,21,0,0

In [48]:
crime_df_final = only_county.drop(columns=['Summary Level_x', 'State Code (FIPS)_x', 'County Code (FIPS)', 'County Subdivision Code (FIPS)_x',
                                              'Place Code (FIPS)_x', 'Consolidtated City Code (FIPS)_x', 'Summary Level_y', 'State Code (FIPS)_y',
                                              'County Code (FIPS)_x', 'County Subdivision Code (FIPS)_y', 'Place Code (FIPS)_y', 'Consolidtated City Code (FIPS)_y'])
crime_df_final

,County,State,year,murder,rape,robbery,aggravated_assaults,burglary,larceny,auto_theft,arson
0,Autauga County,Alabama,2002,0,18,35,48,172,1023,48,13
1,Autauga County,Alabama,2003,3,29,34,95,326,1235,107,3
2,Autauga County,Alabama,2004,0,11,38,103,358,1162,86,3
3,Autauga County,Alabama,2005,0,15,28,67,356,1149,112,1
4,Autauga County,Alabama,2006,1,16,49,85,343,1226,94,3
...,...,...,...,...,...,...,...,...,...,...,...
10506270,Menominee County,Wisconsin,2010,0,0,0,3,24,28,7,1
10506271,Menominee County,Wisconsin,2011,0,0,0,1,21,19,1,0
10506272,Menominee County,Wisconsin,2012,0,0,0,2,31,25,3,0
10506273,Menominee County,Wisconsin,2013,0,1,0,4,16,15,2,0
10506274,Menominee County,Wisconsin,2014,0,0,0,0,12,21,0,0

In [50]:
crime_df_final.to_parquet('Resources/crime_df_final.parquet')